%%-----------------------------------------------------------------------%%
% Description: ctrl.m                                                     %
%   Compute the controller.                                               %
%      m = { A(t)_est' + 1/2 * a(t)_est * delta_y(t)' } * delta_y(t)      %         
%                                                                         %
%   Input:  delta       2x1 image error                                   %
%           M           3x4 camera perspective projection matrix          %
%           T           4x4 endeffecter (frame) current homogenous        %
%                       transform matrix with respect to base frame       %
%           Y           current position(coordinates) of the feature      %
%                       point on the image plane                          %
%           gt          point estimated position w.r.t. base frame        %
%   Output: m           6x1 controller                                    %
%                                                                         %
% Copyright:   Shanghai SJTU Autonomous Robot Lab.                        %
% Author:      Jay Wang                                                   %
% Version:     Beta 1.0.1                                                 %
% Data:        2015.04.09                                                 %
%%-----------------------------------------------------------------------%%

%%
function  m = ctrl (delta,M,T,Y,gt)
m1=M(1,1);m2=M(1,2);m3=M(1,3);m4=M(1,4);m5=M(2,1);m6=M(2,2);m7=M(2,3);m8=M(2,4);m9=M(3,1);m10=M(3,2);m11=M(3,3);m12=M(3,4);
r1=T(1,1);r2=T(1,2);r3=T(1,3);r4=T(2,1);r5=T(2,2);r6=T(2,3);r7=T(3,1);r8=T(3,2);r9=T(3,3);
tx=T(1,4);ty=T(2,4);tz=T(3,4);
u=Y(1);v=Y(2);
d1=delta(1);d2=delta(2);
x=gt(1);y=gt(2);z=gt(3);
m = [                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (- (m10*r4)/2 - (m11*r7)/2 - (m9*r1)/2)*d1^2 + (- r4*(m2 - m10*u) - r1*(m1 - m9*u) - r7*(m3 - m11*u))*d1 + (- (m10*r4)/2 - (m11*r7)/2 - (m9*r1)/2)*d2^2 + (- r4*(m6 - m10*v) - r1*(m5 - m9*v) - r7*(m7 - m11*v))*d2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           (- (m10*r5)/2 - (m11*r8)/2 - (m9*r2)/2)*d1^2 + (- r5*(m2 - m10*u) - r2*(m1 - m9*u) - r8*(m3 - m11*u))*d1 + (- (m10*r5)/2 - (m11*r8)/2 - (m9*r2)/2)*d2^2 + (- r5*(m6 - m10*v) - r2*(m5 - m9*v) - r8*(m7 - m11*v))*d2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           (- (m10*r6)/2 - (m11*r9)/2 - (m9*r3)/2)*d1^2 + (- r6*(m2 - m10*u) - r3*(m1 - m9*u) - r9*(m3 - m11*u))*d1 + (- (m10*r6)/2 - (m11*r9)/2 - (m9*r3)/2)*d2^2 + (- r6*(m6 - m10*v) - r3*(m5 - m9*v) - r9*(m7 - m11*v))*d2;
 ((r4*(m11*(tx + r1*x + r2*y + r3*z) - m9*(tz + r7*x + r8*y + r9*z)))/2 - (r1*(m11*(ty + r4*x + r5*y + r6*z) - m10*(tz + r7*x + r8*y + r9*z)))/2 - (r7*(m10*(tx + r1*x + r2*y + r3*z) - m9*(ty + r4*x + r5*y + r6*z)))/2)*d1^2 + (r4*((m3 - m11*u)*(tx + r1*x + r2*y + r3*z) - (m1 - m9*u)*(tz + r7*x + r8*y + r9*z)) - r7*((m2 - m10*u)*(tx + r1*x + r2*y + r3*z) - (m1 - m9*u)*(ty + r4*x + r5*y + r6*z)) - r1*((m3 - m11*u)*(ty + r4*x + r5*y + r6*z) - (m2 - m10*u)*(tz + r7*x + r8*y + r9*z)))*d1 + ((r4*(m11*(tx + r1*x + r2*y + r3*z) - m9*(tz + r7*x + r8*y + r9*z)))/2 - (r1*(m11*(ty + r4*x + r5*y + r6*z) - m10*(tz + r7*x + r8*y + r9*z)))/2 - (r7*(m10*(tx + r1*x + r2*y + r3*z) - m9*(ty + r4*x + r5*y + r6*z)))/2)*d2^2 + (r4*((m7 - m11*v)*(tx + r1*x + r2*y + r3*z) - (m5 - m9*v)*(tz + r7*x + r8*y + r9*z)) - r7*((m6 - m10*v)*(tx + r1*x + r2*y + r3*z) - (m5 - m9*v)*(ty + r4*x + r5*y + r6*z)) - r1*((m7 - m11*v)*(ty + r4*x + r5*y + r6*z) - (m6 - m10*v)*(tz + r7*x + r8*y + r9*z)))*d2;
 ((r5*(m11*(tx + r1*x + r2*y + r3*z) - m9*(tz + r7*x + r8*y + r9*z)))/2 - (r2*(m11*(ty + r4*x + r5*y + r6*z) - m10*(tz + r7*x + r8*y + r9*z)))/2 - (r8*(m10*(tx + r1*x + r2*y + r3*z) - m9*(ty + r4*x + r5*y + r6*z)))/2)*d1^2 + (r5*((m3 - m11*u)*(tx + r1*x + r2*y + r3*z) - (m1 - m9*u)*(tz + r7*x + r8*y + r9*z)) - r8*((m2 - m10*u)*(tx + r1*x + r2*y + r3*z) - (m1 - m9*u)*(ty + r4*x + r5*y + r6*z)) - r2*((m3 - m11*u)*(ty + r4*x + r5*y + r6*z) - (m2 - m10*u)*(tz + r7*x + r8*y + r9*z)))*d1 + ((r5*(m11*(tx + r1*x + r2*y + r3*z) - m9*(tz + r7*x + r8*y + r9*z)))/2 - (r2*(m11*(ty + r4*x + r5*y + r6*z) - m10*(tz + r7*x + r8*y + r9*z)))/2 - (r8*(m10*(tx + r1*x + r2*y + r3*z) - m9*(ty + r4*x + r5*y + r6*z)))/2)*d2^2 + (r5*((m7 - m11*v)*(tx + r1*x + r2*y + r3*z) - (m5 - m9*v)*(tz + r7*x + r8*y + r9*z)) - r8*((m6 - m10*v)*(tx + r1*x + r2*y + r3*z) - (m5 - m9*v)*(ty + r4*x + r5*y + r6*z)) - r2*((m7 - m11*v)*(ty + r4*x + r5*y + r6*z) - (m6 - m10*v)*(tz + r7*x + r8*y + r9*z)))*d2;
 ((r6*(m11*(tx + r1*x + r2*y + r3*z) - m9*(tz + r7*x + r8*y + r9*z)))/2 - (r3*(m11*(ty + r4*x + r5*y + r6*z) - m10*(tz + r7*x + r8*y + r9*z)))/2 - (r9*(m10*(tx + r1*x + r2*y + r3*z) - m9*(ty + r4*x + r5*y + r6*z)))/2)*d1^2 + (r6*((m3 - m11*u)*(tx + r1*x + r2*y + r3*z) - (m1 - m9*u)*(tz + r7*x + r8*y + r9*z)) - r9*((m2 - m10*u)*(tx + r1*x + r2*y + r3*z) - (m1 - m9*u)*(ty + r4*x + r5*y + r6*z)) - r3*((m3 - m11*u)*(ty + r4*x + r5*y + r6*z) - (m2 - m10*u)*(tz + r7*x + r8*y + r9*z)))*d1 + ((r6*(m11*(tx + r1*x + r2*y + r3*z) - m9*(tz + r7*x + r8*y + r9*z)))/2 - (r3*(m11*(ty + r4*x + r5*y + r6*z) - m10*(tz + r7*x + r8*y + r9*z)))/2 - (r9*(m10*(tx + r1*x + r2*y + r3*z) - m9*(ty + r4*x + r5*y + r6*z)))/2)*d2^2 + (r6*((m7 - m11*v)*(tx + r1*x + r2*y + r3*z) - (m5 - m9*v)*(tz + r7*x + r8*y + r9*z)) - r9*((m6 - m10*v)*(tx + r1*x + r2*y + r3*z) - (m5 - m9*v)*(ty + r4*x + r5*y + r6*z)) - r3*((m7 - m11*v)*(ty + r4*x + r5*y + r6*z) - (m6 - m10*v)*(tz + r7*x + r8*y + r9*z)))*d2;
 ];